In [4]:
# First import PyTorch
import torch

In [5]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [30]:
#Generate Some date
torch.manual_seed(7) #

# Features are 5 random normal variables
features = torch.randn((1,5)) # creates a tensor with shape (1,5), one row and five columns

#True weights for our data, random normal variables again
# Creates another tensor with the same shape as features, 
# again containing values from a normal distribution
weights = torch.randn_like(features)

#and a true bias term
bias = torch.randn((1,1)) # Creates a single value from a normal distribution

In [31]:
y = activation(torch.sum(features* weights)+bias)

In [32]:
print(features)
print(weights)
print(bias)
print(y)
print(features.shape)
print(weights.shape)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])
tensor([[0.1595]])
torch.Size([1, 5])
torch.Size([1, 5])


In [33]:
# torch.mm() and torch.matmul: we prefer torch.mm more often 
# because if something gone wrong we get error message
torch.mm(features,weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at c:\programdata\miniconda3\conda-bld\pytorch_1533090623466\work\aten\src\th\generic/THTensorMath.cpp:2070

In [34]:
# There are three methods primarily to reshape the tensor
# tensor.reshape(), tensor.resize_(), tensor.view()
w_reshape = weights.reshape(5,1) # will return a new tensor with same data as weights with size (5,1)
print(w_reshape)

# In place resize operation changes the original tensor
print(weights)
weights.resize_(5,1) #In place operation
print(weights)
weights.resize_(1,5)
print(weights)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])


In [ ]:
# reduce sum step we dont need to multily and sum manually 
# because matrix multiplication will do that 
y = activation(torch.mm(features, weights.view(5,1))+bias) 


In [35]:
print(y)

tensor([[0.1595]])


In [ ]:
# Matrix multiplication between feature vector and 
# weights matrix gives us the hidden layers
# end of the section